### ISSUE TITLE
Profiles does not apply (everyone see everything)

### ISSUE THREAD

**Issue by execcr** [InfotelGLPI/accounts#19] opened 2017-08-09 07:51 UTC
Plugin Version 2.2.0
GLPI Version 9.1.6

I've noticed only now (and i think that before upgrade from 9.1 to 9.1.6 the behaviour was different, eg users see only the accounts they create) that the users that have self-service profiles see every entry in Accounts, even mine (i'm administrator)

Any hint?

**Comment by execcr** [comment] 2017-08-29 09:04
i've checked and double checked permissions of glpi and everything seems ok.
i had to disabled permission to others users execpt Administrator for now, but i still searching for a solution...

**Comment by Phorms** [comment] 2017-09-08 11:37
Plugin Version 2.2.0
GLPI Version 9.1.6 (9.1.5 untested)

Hi,
we have the same problem. Profiles rights (see all, only my groups) do not apply because the plugin search hook doesn't work.

The function "plugin_accounts_addDefaultWhere" in hook.php does not work with the new commondbtm.class.php. Commit https://github.com/glpi-project/glpi/commit/cf911a8b286f34c17b2a3bcf681b7107d0130a17#diff-7f569484c496f62a6ccf54647fed2b1b changed the old hook system.

We reverted the commit to to get the plugin to respect the profile rights, but I'm pretty sure it will break other stuff.

Please update the search hook to support GLPI 9.1.5+.

Thanks

**Comment by amma35** [comment] 2017-12-14 14:01
Hi, 
I do not reproduce your problem.

Can you detail me the steps to display a password without the rights to the plugin account?

**Comment by Phorms** [comment] 2017-12-20 15:24
Hi,
it was an GLPI Bug (commit above), not the accounts plugin. The bug is fixed now (master branch and maybe earlier).

As you can see in release 9.1.6 (picture) there is a missing break right after `$condition = $out;` in glpi/inc/search.class.php. I added it in our code (line 2784).
![glpi_bug](https://user-images.githubusercontent.com/14980311/34213439-8145c26c-e59f-11e7-8996-6d57cdc0f179.PNG)

The plugin condition was "forgotten" / deleted because of the following `return "";`, which is removed in newer versions. Without an condition every account was visible.

**Comment by amma35** [comment] 2017-12-20 15:29
Hi,
Ok, I tested with version 9.1.1 of GLPI.
Thank you for your return and correction.

**Closed by amma35** 2017-12-20 15:29 UTC
